---
title: "eDNA"
author: "Jay T Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Analysis of quantitative PCR data to test whether the abundance of bacterial communities is affected by extracellular DNA

# Setup Work Environment 
```{r}
rm(list=ls())
getwd()
setwd("~/GitHub/eDNA")
require("plyr")
```

# Load data and calcualte corrected copy number
```{r}
eDNA.raw <- read.table("data/eDNA_qPCR.txt", sep = "\t", header = T)

# Correct for dilutions
copies.corr <- eDNA.raw[,7] * eDNA.raw[,8] * (eDNA.raw[,9]/eDNA.raw[,10])

# Make new dataframe with corrected copy numbers
eDNA.corr <- data.frame(eDNA.raw, copies.corr)
```

# Take mean of technical replicates and sort
```{r}
# Use `aggregate` to return means of technical reps for each sample
eDNA <- aggregate(eDNA.corr$copies.corr ~ eDNA.corr$sample + eDNA.corr$sample_name + eDNA.corr$env + eDNA.corr$treat, eDNA.corr, mean)

# Sort by sample number
eDNA <- eDNA[order(eDNA[,1]) ,]

# Rename columns
colnames(eDNA) <- c("sample.number", "sample.name", "env", "treat", "copy.number")
```

# Calculate proportion of degradable DNA per sample and test differences
```{r}
# Use `ddply` to return the DNase-1 degradable proportion of 16S rRNA gene copy
eDNA.prop <- ddply(eDNA, .(sample.number, sample.name, env), summarize, prop = 1 - ((copy.number[treat == "E"]) / (copy.number[treat == "C"])))

# Sort by environment
eDNA.prop <- eDNA.prop[order(eDNA.prop[,3]) ,]

# Remove duplicate T7 soil sample
eDNA.prop <- eDNA.prop[ ! eDNA.prop$sample.name == "T7Core", ]

# Two samples (cat feces [32], human feces [28], T7Core) have negative proportions
# Set these to zero (i.e., no eDNA)
eDNA.prop$prop <- ifelse(eDNA.prop$prop < 0, 0, eDNA.prop$prop)

# Use glm to test whether amount of eDNA differs among environments
eDNA.prop.test <- lm(prop ~ env, data = eDNA.prop)
summary(eDNA.prop.test)

# Calculate means, sem, and sample size by enviroment
eDNA.mean <- aggregate(eDNA.prop$prop ~ eDNA.prop$env, eDNA.prop, mean)
eDNA.n <- aggregate(eDNA.prop$prop ~ eDNA.prop$env, eDNA.prop, length)
sem <- function(x, ...){sd(x, ...)/sqrt(length(na.omit(x)))}
eDNA.sem <- aggregate(eDNA.prop$prop ~ eDNA.prop$env, eDNA.prop, sem)

# Make table of proportion eDNA by environment
eDNA.table <- data.frame(eDNA.mean, eDNA.sem[,2], eDNA.n[,2])
colnames(eDNA.table) <- c("env", "mean", "sem", "n")
eDNA.table <- eDNA.table[order(eDNA.table[,2]) ,]
```

# Make bot plot with error bars by environment
```{r}
png(filename="figures/qPCR.bar.png",
    width = 800, height = 800, res = 96*2)
plot.new()
par(lwd = 2)
bp <- barplot(eDNA.table$mean, ylim =c(0, 0.6), 
              pch = 15, cex = 1.25, las = 1, cex.lab = 1.25, cex.axis = 1, 
              col = "white", axis.lty = 1, lwd = 2, xlab = NA, 
              ylab = "Proportion eDNA",
              names.arg = c("Gut", "Soil", "Sediment", "Water"), cex.names = 0.9)
              box(lwd = 2)
arrows(x0 = bp, y0 = eDNA.table$mean, y1 = eDNA.table$mean - eDNA.table$sem, angle = 90,
       length = 0.1, lwd = 2)
arrows(x0 = bp, y0 = eDNA.table$mean, y1 = eDNA.table$mean + eDNA.table$sem, angle = 90,
       length=0.1, lwd = 2)

# Close Plot Device
dev.off()
graphics.off()
```

```{r}
png(filename="figures/qPCR.nonbar.png",
    width = 800, height = 800, res = 96*2)

plot.new()
non.bp <- plot(eDNA.table$mean, ylim = c(0, 0.6), 
      xlim = c(0.5, 4.5), pch = 22, bg = "white", lwd = 2, 
      cex = 3, yaxt = "n", xaxt = "n", cex.lab = 2, cex.axis = 1.5, 
      las = 1, ylab = "", xlab = "")
      box(lwd = 2)

mtext(expression('Proportion eDNA'), side = 2, 
      outer = TRUE, cex = 1.5, line = -1.5, adj = 0.5)

# Major Axes
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
    labels = c(0.0, 0.2, 0.4, 0.6), at = c(0.0, 0.2, 0.4, 0.6))
 
axis(side = 4, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at=c(0.0, 0.2, 0.4, 0.6), labels = F)

axis(side = 1, lwd.ticks = 2, cex.axis = 0.9, las = 1,
    labels = c("Gut", "Soil", "Sediment", "Water"), at = c(1, 2, 3, 4))

axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    at = c(1, 2, 3, 4), labels = F)

arrows(x0 = c(1, 2, 3, 4), y0 = eDNA.table$mean, y1 = eDNA.table$mean - eDNA.table$sem, angle = 90,
       length = 0.1, lwd = 2)

arrows(x0 = c(1,2,3,4), y0 = eDNA.table$mean, y1 = eDNA.table$mean + eDNA.table$sem, angle = 90,
       length=0.1, lwd = 2)

# Close Plot Device
dev.off()
graphics.off()
```