---
title: "eDNA"
author: "Jay T. Lennon, Mario E. Muscarella, ..."
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

A model approach to relic DNA.



# Sampling Mixing Model: Different SAD
```{r}
gamma1 <- rlnorm(n=10000, meanlog = 1, sdlog = 0.98)
gamma1 <- gamma1[rev(order(gamma1))]
gamma2 <- rlnorm(n=10000, meanlog = 1, sdlog = 1.5)
gamma2 <- gamma2[rev(order(gamma2))]
gamma3 <- rlnorm(n=10000, meanlog = 1, sdlog = 0.5)
gamma3 <- gamma3[rev(order(gamma3))]


plot(log10(gamma1), col = "forestgreen",
     main = "Species Abundance Distributions",
     xlab = "Species Index", ylab = "Log Probability",
     las = 1)
points(log10(gamma2), col = "red")
points(log10(gamma3), col = "blue")

# Define OTUs
otus <- paste("OTU", sprintf("%05d", seq(1:length(gamma1))), sep = "")

# Initiate Communities
site1 <- sample(otus, size = 100000, replace = T, prob = gamma1)
site2 <- sample(otus, size = 100000, replace = T, prob = gamma2)
site3 <- sample(otus, size = 100000, replace = T, prob = gamma3)

site1.t <- table(site1); site2.t <- table(site2); site3.t <- table(site3)

specnumber(site1.t)
specnumber(site2.t)
specnumber(site3.t)

ratio.tab <- matrix(NA, nrow = 4, ncol = 100)
rownames(ratio.tab) <- c("Null", "Uneven", "Even", "Proportion")

size.comm <- 1000000
props <- seq(size.comm/100, size.comm, 10000)

for(i in 1:length(props)){
  n <- props[i]
  # Initialize
  temp.null <- c(sample(otus, size = size.comm, replace = T, prob = gamma1))
  temp.uneven <- c(sample(otus, size = size.comm, replace = T, prob = gamma1), 
                   sample(otus, size = n, replace = T, prob = gamma2))
  temp.even <- c(sample(otus, size = size.comm, replace = T, prob = gamma1), 
                 sample(otus, size = n, replace = T, prob = gamma3))
  tab1 <- table(temp.null)
  tab2 <- table(temp.uneven)
  tab3 <- table(temp.even)

  sbys <- matrix(NA, ncol = length(otus), nrow = 5)
  colnames(sbys) <- otus
  rownames(sbys) <- c("site1", "site2", "site3",
                    "comb1", "comb2")

  for(j in 1:dim(sbys)[2]){
    if (otus[j] %in% names(tab1)){
      sbys[1, j] <- tab1[which(names(tab1) == otus[j])]
    } else {sbys[1, j] <- 0}
    
    if (otus[j] %in% names(tab2)){
      sbys[2, j] <- tab2[which(names(tab2) == otus[j])]
    } else {sbys[2, j] <- 0}
    
    if (otus[j] %in% names(tab3)){
      sbys[3, j] <- tab3[which(names(tab3) == otus[j])]
    } else {sbys[3, j] <- 0}
    
  }

  sbys[4, ] <- sbys[1, ] + sbys[2, ]
  sbys[5, ] <- sbys[1, ] + sbys[3, ]
  
  sbys2 <- rrarefy(sbys, 10000)
  
  rich <- specnumber(sbys2)
  
  ratio.tab[1, i] <- round(rich[1]/rich[1], 2)
  ratio.tab[2, i] <- round(rich[4]/rich[1], 2)
  ratio.tab[3, i] <- round(rich[5]/rich[1], 2)
  ratio.tab[4, i] <- props[i] / size.comm
  print(paste(i, " of ", dim(ratio.tab)[2], sep = ""))
}

par(mar = c(4, 4, 1, 1) + 0.5)
plot(ratio.tab[4, ], ratio.tab[1, ], type = 'n',
     xlab = "Proportion of Relic DNA",
     ylab = "Richness Ratio",
     ylim = c(0.9,1.1), las = 1)
points(ratio.tab[4, ], ratio.tab[2, ], pch = 22,bg = "gray40")
points(ratio.tab[4, ], ratio.tab[3, ], pch = 21, bg = "gray60")
abline(h=1, lty = 3, lwd = 1.5)
legend("topleft", c("Relic Less Even", "Relic More Even"), 
       pch = c(22, 21), pt.bg = c("gray40", "gray60"), bty = "n",
       cex = 0.8)
```

# Sampling Mixing Model: Different Ranks
```{r}
gamma1 <- rlnorm(n=10000, meanlog = 1, sdlog = 0.98)
gamma1 <- gamma1[rev(order(gamma1))]
gamma2 <- gamma2[(order(gamma1))]
ord1 <- rev(order(gamma3))
seqs <- seq(0, max(ord1), 100)
ord3 <- vector()
for(i in 2:length(seqs)){
  ord3 <- c(ord3, sample(seq(seqs[i - 1], seqs[i])))
}
gamma3 <- gamma3[rev(order(gamma3))]


plot(log10(gamma1), col = "forestgreen",
     main = "Species Abundance Distributions",
     xlab = "Species Index", ylab = "Log Probability",
     las = 1)
points(log10(gamma2), col = "red")
points(log10(gamma3), col = "blue")

# Define OTUs
otus <- paste("OTU", sprintf("%05d", seq(1:length(gamma1))), sep = "")

# Initiate Communities
site1 <- sample(otus, size = 100000, replace = T, prob = gamma1)
site2 <- sample(otus, size = 100000, replace = T, prob = gamma2)
site3 <- sample(otus, size = 100000, replace = T, prob = gamma3)

site1.t <- table(site1); site2.t <- table(site2); site3.t <- table(site3)

specnumber(site1.t)
specnumber(site2.t)
specnumber(site3.t)

ratio.tab <- matrix(NA, nrow = 4, ncol = 100)
rownames(ratio.tab) <- c("Null", "Uneven", "Even", "Proportion")

size.comm <- 1000000
props <- seq(size.comm/100, size.comm, 10000)

for(i in 1:length(props)){
  n <- props[i]
  # Initialize
  temp.null <- c(sample(otus, size = size.comm, replace = T, prob = gamma1))
  temp.uneven <- c(sample(otus, size = size.comm, replace = T, prob = gamma1), 
                   sample(otus, size = n, replace = T, prob = gamma2))
  temp.even <- c(sample(otus, size = size.comm, replace = T, prob = gamma1), 
                 sample(otus, size = n, replace = T, prob = gamma3))
  tab1 <- table(temp.null)
  tab2 <- table(temp.uneven)
  tab3 <- table(temp.even)

  sbys <- matrix(NA, ncol = length(otus), nrow = 5)
  colnames(sbys) <- otus
  rownames(sbys) <- c("site1", "site2", "site3",
                    "comb1", "comb2")

  for(j in 1:dim(sbys)[2]){
    if (otus[j] %in% names(tab1)){
      sbys[1, j] <- tab1[which(names(tab1) == otus[j])]
    } else {sbys[1, j] <- 0}
    
    if (otus[j] %in% names(tab2)){
      sbys[2, j] <- tab2[which(names(tab2) == otus[j])]
    } else {sbys[2, j] <- 0}
    
    if (otus[j] %in% names(tab3)){
      sbys[3, j] <- tab3[which(names(tab3) == otus[j])]
    } else {sbys[3, j] <- 0}
    
  }

  sbys[4, ] <- sbys[1, ] + sbys[2, ]
  sbys[5, ] <- sbys[1, ] + sbys[3, ]
  
  sbys2 <- rrarefy(sbys, 10000)
  
  rich <- specnumber(sbys2)
  
  ratio.tab[1, i] <- round(rich[1]/rich[1], 2)
  ratio.tab[2, i] <- round(rich[4]/rich[1], 2)
  ratio.tab[3, i] <- round(rich[5]/rich[1], 2)
  ratio.tab[4, i] <- props[i] / size.comm
  print(paste(i, " of ", dim(ratio.tab)[2], sep = ""))
}

par(mar = c(4, 4, 1, 1) + 0.5)
plot(ratio.tab[4, ], ratio.tab[1, ], type = 'n',
     xlab = "Proportion of Relic DNA",
     ylab = "Richness Ratio",
     ylim = c(0.9,1.2), las = 1)
points(ratio.tab[4, ], ratio.tab[2, ], pch = 22,bg = "gray40")
points(ratio.tab[4, ], ratio.tab[3, ], pch = 21, bg = "gray60")
abline(h=1, lty = 3, lwd = 1.5)
legend("topleft", c("Reversed SAD", "Window Randomized SAD"), 
       pch = c(22, 21), pt.bg = c("gray40", "gray60"), bty = "n",
       cex = 0.8)
```

# Sampling Mixing Model: Different N
```{r}
gamma1 <- rlnorm(n=10000, meanlog = 1, sdlog = 0.98)
gamma1 <- gamma1[rev(order(gamma1))]
gamma2 <- rlnorm(n=100000, meanlog = 1, sdlog = 0.98)
gamma2 <- gamma2[rev(order(gamma2))]
gamma3 <- rlnorm(n=1000, meanlog = 1, sdlog = 0.98)
gamma3 <- gamma3[rev(order(gamma3))]


plot(log10(gamma1), col = "forestgreen",
     main = "Species Abundance Distributions",
     xlab = "Species Index", ylab = "Log Probability",
     las = 1)
points(log10(gamma2), col = "red")
points(log10(gamma3), col = "blue")

# Define OTUs
otus1 <- paste("OTU", sprintf("%05d", seq(1:length(gamma1))), sep = "")
otus2 <- paste("OTU", sprintf("%05d", seq(1:length(gamma2))), sep = "")
otus3 <- paste("OTU", sprintf("%05d", seq(1:length(gamma3))), sep = "")


# Initiate Communities
site1 <- sample(otus1, size = 100000, replace = T, prob = gamma1)
site2 <- sample(otus2, size = 100000, replace = T, prob = gamma2)
site3 <- sample(otus3, size = 100000, replace = T, prob = gamma3)

site1.t <- table(site1); site2.t <- table(site2); site3.t <- table(site3)

specnumber(site1.t)
specnumber(site2.t)
specnumber(site3.t)

ratio.tab <- matrix(NA, nrow = 4, ncol = 100)
rownames(ratio.tab) <- c("Null", "Uneven", "Even", "Proportion")

size.comm <- 1000000
props <- seq(size.comm/100, size.comm, 10000)

for(i in 1:length(props)){
  n <- props[i]
  # Initialize
  temp.null <- c(sample(otus1, size = size.comm, replace = T, prob = gamma1))
  temp.uneven <- c(sample(otus2, size = size.comm, replace = T, prob = gamma2), 
                   sample(otus2, size = n, replace = T, prob = gamma2))
  temp.even <- c(sample(otus3, size = size.comm, replace = T, prob = gamma3), 
                 sample(otus3, size = n, replace = T, prob = gamma3))
  tab1 <- table(temp.null)
  tab2 <- table(temp.uneven)
  tab3 <- table(temp.even)

  sbys <- matrix(NA, ncol = length(otus), nrow = 5)
  colnames(sbys) <- otus
  rownames(sbys) <- c("site1", "site2", "site3",
                    "comb1", "comb2")

  for(j in 1:dim(sbys)[2]){
    if (otus[j] %in% names(tab1)){
      sbys[1, j] <- tab1[which(names(tab1) == otus[j])]
    } else {sbys[1, j] <- 0}
    
    if (otus[j] %in% names(tab2)){
      sbys[2, j] <- tab2[which(names(tab2) == otus[j])]
    } else {sbys[2, j] <- 0}
    
    if (otus[j] %in% names(tab3)){
      sbys[3, j] <- tab3[which(names(tab3) == otus[j])]
    } else {sbys[3, j] <- 0}
    
  }

  sbys[4, ] <- sbys[1, ] + sbys[2, ]
  sbys[5, ] <- sbys[1, ] + sbys[3, ]
  
  sbys2 <- rrarefy(sbys, 10000)
  
  rich <- specnumber(sbys2)
  
  ratio.tab[1, i] <- round(rich[1]/rich[1], 2)
  ratio.tab[2, i] <- round(rich[4]/rich[1], 2)
  ratio.tab[3, i] <- round(rich[5]/rich[1], 2)
  ratio.tab[4, i] <- props[i] / size.comm
  print(paste(i, " of ", dim(ratio.tab)[2], sep = ""))
}

par(mar = c(4, 4, 1, 1) + 0.5)
plot(ratio.tab[4, ], ratio.tab[1, ], type = 'n',
     xlab = "Proportion of Relic DNA",
     ylab = "Richness Ratio",
     ylim = c(0.9,1.1), las = 1)
points(ratio.tab[4, ], ratio.tab[2, ], pch = 22,bg = "gray40")
points(ratio.tab[4, ], ratio.tab[3, ], pch = 21, bg = "gray60")
abline(h=1, lty = 3, lwd = 1.5)
legend("topleft", c("Relic Less Even", "Relic More Even"), 
       pch = c(22, 21), pt.bg = c("gray40", "gray60"), bty = "n",
       cex = 0.8)
```



# Sample Stocastic Model
```{r}
# Create Regional Species Pool
gamma <- rlnorm(n=100000, meanlog = 1, sdlog = 0.98)
gamma <- gamma1[rev(order(gamma1))]

# Define OTUs
otus <- paste("OTU", sprintf("%05d", seq(1:length(gamma))), sep = "")

# Initiate Communitie
active <- sample(otus, size = 100000, replace = T, prob = gamma)

# Initiate Relic Pool
relic <- vector()

t <- 0

while(t < 100){
  # Store Initial Status
  len <- length(active)
  rlen <- length(relic)
  
  # Random Community Growth
  active <- c(active, active[c(sample(c(1:len), len*0.09, replace = F))])
  
  # Random Immigration from Regional
  active <- c(active, sample(otus, size = len*0.01, replace = T, prob = gamma))
  
  # Random Relic Generation
  temp <- sample(c(1:len), len*0.1, replace = F)
  relic <- c(relic, active[temp])
  active <- active[-c(temp)]
  
  # Random Relic Degradation
  if(rlen > 0){
    deg <- runif(rlen)
    #deg <- rexp(rlen)
    relic <- relic[-c(sample(c(1:rlen), rlen*0.1, replace = F, prob = deg))]
  }

  
  # Time Counter
  t <- t+1
  
  # Print N
  print(paste("N1 = ", length(active),  
              "; Nr1 = ", length(relic), sep = ""))
}


active.t <- table(active); 
relic.t <- table(relic)

sbys <- matrix(NA, ncol = length(otus), nrow = 3)
colnames(sbys) <- otus
rownames(sbys) <- c("active",
                    "relic",
                    "comb")

for(i in 1:dim(sbys)[2]){
  if (otus[i] %in% names(active.t)){
    sbys[1, i] <- active.t[which(names(active.t) == otus[i])]
  } else {sbys[1, i] <- 0}
  
  if (otus[i] %in% names(relic.t)){
    sbys[2, i] <- relic.t[which(names(relic.t) == otus[i])]
  } else {sbys[2, i] <- 0}

}

sbys[3, ] <- sbys[1, ] + sbys[2, ]

sbys2 <- rrarefy(sbys, 10000)

rich <- specnumber(sbys2)

ratio <- round(rich[3]/rich[1], 2)


rich
ratio
```

# Original Stocastic Model
```{r}
gamma1 <- rlnorm(n=10000, meanlog = 1, sdlog = 0.98)
gamma1 <- gamma1[rev(order(gamma1))]
gamma2 <- rlnorm(n=10000, meanlog = 1, sdlog = 2)
gamma2 <- gamma2[rev(order(gamma2))]
gamma3 <- rlnorm(n=10000, meanlog = 1, sdlog = 0.5)
gamma3 <- gamma3[rev(order(gamma3))]
#gamma2 <- rlnorm(n=10000, meanlog = 1, sdlog = 0.98)
#gamma2 <- gamma2

plot(log10(gamma1), col = "blue")
points(log10(gamma2), col = "red")
points(log10(gamma3), col = "forestgreen")

# Define OTUs
otus <- paste("OTU", sprintf("%05d", seq(1:length(gamma1))), sep = "")

# Initiate Communities
site1 <- sample(otus, size = 100000, replace = T, prob = gamma1)
site2 <- sample(otus, size = 100000, replace = T, prob = gamma1)
site3 <- sample(otus, size = 100000, replace = T, prob = gamma1)

# Initiate Relic Pool
relic1 <- vector()
relic2 <- vector()
relic3 <- vector()

t <- 0

while(t < 100){
  # Random Community Growth
  len1 <- length(site1)
  len2 <- length(site2)
  len3 <- length(site3)
  rlen1 <- length(relic1)
  rlen2 <- length(relic2)
  rlen3 <- length(relic3)
  site1 <- c(site1, site1[c(sample(c(1:len1), len1*0.1, replace = F))])
  site2 <- c(site2, site2[c(sample(c(1:len2), len2*0.1, replace = F))])
  site3 <- c(site3, site3[c(sample(c(1:len3), len3*0.1, replace = F))])

  # Random Relic Generation
  temp1 <- sample(c(1:len1), len1*0.1, replace = F)
  temp2 <- sample(c(1:len2), len2*0.1, replace = F)
  temp3 <- sample(c(1:len3), len3*0.1, replace = F)
  imm2 <- sample(otus, size = 10000, replace = T, prob = gamma2)
  imm3 <- sample(otus, size = 10000, replace = T, prob = gamma3)
  relic1 <- c(relic1, site1[temp1])
  relic2 <- c(relic2, site2[temp2], imm2)
  relic3 <- c(relic3, site3[temp3], imm3)
  site1 <- site1[-c(temp1)]
  site2 <- site2[-c(temp2)]
  site3 <- site3[-c(temp3)]

  # Random Relic Degradation
  if(rlen1 > 0){
    relic1 <- relic1[-c(sample(c(1:rlen1), rlen1*0.1, replace = F))]
    }
  if(rlen2 > 0){
    relic2 <- relic2[-c(sample(c(1:rlen2), rlen2*0.1, replace = F))]
    }
  if(rlen3 > 0){
    relic3 <- relic3[-c(sample(c(1:rlen3), rlen3*0.1, replace = F))]
    }

  # Time Counter
  t <- t+1
  
  # Print N
  print(paste("N1 = ", length(site1), "; N2 = ", length(site2), 
              "; Nr1 = ", length(relic1), "; Nr2 = ", length(relic2), sep = ""))
}


site1.t <- table(site1); site2.t <- table(site2); site3.t <- table(site3)
relic1.t <- table(relic1); relic2.t <- table(relic2); relic3.t <- table(relic3)

sbys <- matrix(NA, ncol = length(otus), nrow = 9)
colnames(sbys) <- otus
rownames(sbys) <- c("site1", "site2", "site3", 
                    "relic1", "relic2", "relic3",
                    "comb1", "comb2", "comb3")

for(i in 1:dim(sbys)[2]){
  if (otus[i] %in% names(site1.t)){
    sbys[1, i] <- site1.t[which(names(site1.t) == otus[i])]
  } else {sbys[1, i] <- 0}
  
  if (otus[i] %in% names(site2.t)){
    sbys[2, i] <- site2.t[which(names(site2.t) == otus[i])]
  } else {sbys[2, i] <- 0}
  
  if (otus[i] %in% names(site3.t)){
    sbys[3, i] <- site3.t[which(names(site3.t) == otus[i])]
  } else {sbys[3, i] <- 0}
  
  if (otus[i] %in% names(relic1.t)){
    sbys[4, i] <- relic1.t[which(names(relic1.t) == otus[i])]
  } else {sbys[4, i] <- 0}
  
  if (otus[i] %in% names(relic2.t)){
    sbys[5, i] <- relic2.t[which(names(relic2.t) == otus[i])]
  } else {sbys[5, i] <- 0}
  
  if (otus[i] %in% names(relic3.t)){
    sbys[6, i] <- relic3.t[which(names(relic3.t) == otus[i])]
  } else {sbys[6, i] <- 0}

}

sbys[7, ] <- sbys[1, ] + sbys[4, ]
sbys[8, ] <- sbys[2, ] + sbys[5, ]
sbys[9, ] <- sbys[3, ] + sbys[6, ]

sbys2 <- rrarefy(sbys, 10000)

rich <- specnumber(sbys2)

ratio1 <- round(rich[7]/rich[1], 2)
ratio2 <- round(rich[8]/rich[2], 2)
ratio3 <- round(rich[9]/rich[3], 2)

rich
ratio1
ratio2
ratio3
```

